GET http://localhost:3003/api/blogs 


###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MjBiYWQ3YjBmYTEyZjI3YjIzNGJjNjUiLCJpYXQiOjE2NDQ5MzY3MzB9.BP_WVhjSfspyNFeZ6O6H3O-n6QCGcmnmYe2T8iGdEKY

{
    "title": "Second Post",
    "author": "admin",
    "url": "blogs/2",
    "likes": 11
}
