GET http://localhost:3003/api/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MjBiYWQ3YjBmYTEyZjI3YjIzNGJjNjUiLCJpYXQiOjE2NDUwMjU3MDF9.l_revNu0M_t4U6ZpxNW4itev5nRzRigZx_Q0lij3wDU
###
GET http://localhost:3003/api/users/62090c25f2ca3c6d53ba809b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MjBiYWQ3YjBmYTEyZjI3YjIzNGJjNjUiLCJpYXQiOjE2NDUwMTI3MTl9.6D2xiV0_nk78JYdvMwYs_B5UZtUtbvHRym1V-WdugYw

###
POST http://localhost:3003/api/users
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MjBiYWQ3YjBmYTEyZjI3YjIzNGJjNjUiLCJpYXQiOjE2NDUwMTI3MTl9.6D2xiV0_nk78JYdvMwYs_B5UZtUtbvHRym1V-WdugYw


{
    "username": "user2",
    "name": "User 2",
    "password": "user2"
}